/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: shuvalov.di (https://sketchfab.com/shuvalov.di)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/books-with-magnifier-cc153ce6258b4e538d9fc7da5b5d0fe4
Title: Books with magnifier
*/

"use client";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const BookModel = React.memo(function BookModel(props) {
  const { nodes, materials } = useGLTF("/models/ss-transformed.glb");
  const modelRef = useRef();

  // Keep same rotation animation
  useFrame(() => {
    if (modelRef.current) {
      modelRef.current.rotation.y += 0.004;
    }
  });

  return (
    <group
      {...props}
      dispose={null}
      ref={modelRef}
      scale={[9.2, 9.2, 9.2]} // same as your hat scaling
      rotation={[0.4, -1, 0]} // same as hat rotation
      position={[0, 0, 0]} // same as hat position
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magnifier_Magnifier_0.geometry}
        material={materials.Magnifier}
        position={[-0.01, 0.033, -0.047]}
        rotation={[-1.58, 0.006, -0.544]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Open_book_Open_book_Mat_0.geometry}
        material={materials.Open_book_Mat}
        position={[0, 0, -0.047]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Book_3_Book_3_Mat_0.geometry}
        material={materials.Book_3_Mat}
        position={[0.079, 0.07, 0.247]}
        rotation={[Math.PI, -1.164, 0]}
        scale={0.745}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Book_2_Book_2_Mat_0.geometry}
        material={materials.Book_2_Mat}
        position={[0.198, 0, 0.097]}
        rotation={[-Math.PI / 2, 0, -2.055]}
        scale={0.745}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Book_1_Book_1_Mat_0.geometry}
        material={materials.Book_1_Mat}
        position={[0.012, 0.024, 0.179]}
        rotation={[Math.PI, 1.426, 0]}
        scale={0.745}
      />
    </group>
  );
});

export default BookModel;

useGLTF.preload("/models/ss-transformed.glb");